#!/bin/bash

# Pre-commit checks script
# Runs code quality checks only on changed files (excluding deleted and autogenerated files)

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    local status=$1
    local message=$2
    case $status in
        "info") echo -e "${BLUE}ℹ️  ${message}${NC}" ;;
        "success") echo -e "${GREEN}✅ ${message}${NC}" ;;
        "warning") echo -e "${YELLOW}⚠️  ${message}${NC}" ;;
        "error") echo -e "${RED}❌ ${message}${NC}" ;;
    esac
}

# Get changed Python files (excluding deleted files)
print_status "info" "Detecting changed Python files..."

# Get both staged and unstaged changes, excluding deleted files
CHANGED_PY_FILES=$(git diff --name-only --diff-filter=ACMR HEAD -- '*.py' 2>/dev/null || true)
STAGED_PY_FILES=$(git diff --cached --name-only --diff-filter=ACMR HEAD -- '*.py' 2>/dev/null || true)

# Combine and deduplicate
ALL_CHANGED_PY_FILES=$(echo -e "$CHANGED_PY_FILES\n$STAGED_PY_FILES" | sort -u | grep -v '^$' || true)

# Filter out autogenerated files (common patterns)
FILTERED_PY_FILES=$(echo "$ALL_CHANGED_PY_FILES" | grep -v -E '(__pycache__|\.pyc$|\.pyo$|\.pyd$|migrations/|build/|dist/|\.egg-info/|\.pytest_cache/|\.mypy_cache/|\.ruff_cache/|\.coverage|htmlcov/|\.venv/|venv/|env/)' || true)

if [ -z "$FILTERED_PY_FILES" ]; then
    print_status "info" "No Python files changed. Checking other files..."
else
    print_status "info" "Found $(echo "$FILTERED_PY_FILES" | wc -l | tr -d ' ') changed Python files"
fi

# Get changed config files
CONFIG_FILES=$(git diff --name-only --diff-filter=ACMR HEAD -- '*.toml' '*.yaml' '*.yml' '*.json' '*.md' 2>/dev/null || true)
STAGED_CONFIG_FILES=$(git diff --cached --name-only --diff-filter=ACMR HEAD -- '*.toml' '*.yaml' '*.yml' '*.json' '*.md' 2>/dev/null || true)
ALL_CONFIG_FILES=$(echo -e "$CONFIG_FILES\n$STAGED_CONFIG_FILES" | sort -u | grep -v '^$' || true)

# Track overall status
OVERALL_STATUS=0

# Run ruff check on changed Python files
if [ -n "$FILTERED_PY_FILES" ]; then
    print_status "info" "Running ruff check..."
    if echo "$FILTERED_PY_FILES" | xargs uvx ruff check --no-fix 2>&1; then
        print_status "success" "Ruff check passed"
    else
        print_status "error" "Ruff check found issues"
        OVERALL_STATUS=1
    fi
    
    # Run ruff format check
    print_status "info" "Running ruff format check..."
    if echo "$FILTERED_PY_FILES" | xargs uvx ruff format --check 2>&1; then
        print_status "success" "Code formatting is correct"
    else
        print_status "warning" "Code needs formatting (can be auto-fixed)"
        OVERALL_STATUS=1
    fi
    
    # Run type checking with upright
    print_status "info" "Running type check with pyright..."
    if uvx pyright $FILTERED_PY_FILES 2>&1; then
        print_status "success" "Type check passed"
    else
        print_status "error" "Type check found issues"
        OVERALL_STATUS=1
    fi
    
    # Run deadcode check
    print_status "info" "Running deadcode check..."
    # For deadcode, we need to check each file individually as it doesn't take multiple files well
    DEADCODE_ISSUES=0
    for file in $FILTERED_PY_FILES; do
        if uvx deadcode "$file" 2>&1 | grep -q "No dead code found"; then
            :  # No issues in this file
        else
            print_status "warning" "Dead code found in $file"
            uvx deadcode "$file" 2>&1 | grep -v "No dead code found" || true
            DEADCODE_ISSUES=1
        fi
    done
    
    if [ $DEADCODE_ISSUES -eq 0 ]; then
        print_status "success" "No dead code found"
    else
        OVERALL_STATUS=1
    fi
fi

# Run pytest if test files exist
print_status "info" "Checking for test files..."
TEST_FILES=$(find . -name "test_*.py" -o -name "*_test.py" -o -path "*/tests/*" -type f | grep -E "\.py$" | grep -v ".venv" | grep -v "node_modules" | grep -v "__pycache__" || true)

if [ -n "$TEST_FILES" ]; then
    print_status "info" "Running pytest..."
    if uv run pytest 2>&1; then
        print_status "success" "All tests passed"
    else
        print_status "error" "Tests failed"
        OVERALL_STATUS=1
    fi
else
    print_status "info" "No test files found, skipping pytest"
fi

# Check if there are any changes to stage
print_status "info" "Checking git status..."
if git diff --quiet && git diff --cached --quiet; then
    print_status "warning" "No changes to commit"
    exit 0
fi

# Summary
echo ""
if [ $OVERALL_STATUS -eq 0 ]; then
    print_status "success" "All checks passed! ✨"
else
    print_status "warning" "Some checks failed or need attention"
    echo ""
    echo "Suggested fixes:"
    if echo "$FILTERED_PY_FILES" | xargs uvx ruff format --check &>/dev/null; then
        :
    else
        echo "  - Run: uvx ruff format . (to fix formatting)"
    fi
    if echo "$FILTERED_PY_FILES" | xargs uvx ruff check --fix-only --exit-zero &>/dev/null; then
        echo "  - Run: uvx ruff check --fix . (to fix auto-fixable issues)"
    fi
fi

# Show changed files summary
echo ""
print_status "info" "Changed files summary:"
git status --short | grep -v '^D' || true

exit $OVERALL_STATUS